-- MySQL Script generated by MySQL Workbench
-- Tue Oct  6 11:40:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pokemons
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pokemons
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pokemons` DEFAULT CHARACTER SET utf8 ;
USE `Pokemons` ;

-- -----------------------------------------------------
-- Table `Pokemons`.`Pokemon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pokemons`.`Pokemon` ;

CREATE TABLE IF NOT EXISTS `Pokemons`.`Pokemon` (
  `id` INT NOT NULL,
  `pokemonName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pokemons`.`Elements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pokemons`.`Elements` ;

CREATE TABLE IF NOT EXISTS `Pokemons`.`Elements` (
  `id` INT NOT NULL,
  `element` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pokemons`.`PokemonElements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pokemons`.`PokemonElements` ;

CREATE TABLE IF NOT EXISTS `Pokemons`.`PokemonElements` (
 pokemonId int not null,
 elementId int not null,
 foreign key (pokemonId) references pokemons.pokemon(id),
 foreign key (elementId) references pokemons.elements(id))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
